[package]
name = "browser-cdp"
version = "0.1.1"
edition = "2024"
license-file = "../../COMMERCIAL-LICENSE.md"

[dependencies]
async-trait = { workspace = true }
blob-core = { path = "../blob-core" }
futures-util = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
url = "2.5"
