[package]
name = "smb-sidecar-host"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
anyhow.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true
