#!/usr/bin/env bash
# SPDX-License-Identifier: LicenseRef-CCBG-Commercial
# Copyright (c) 2026 walky
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_ID=""
REPO="${GITHUB_REPOSITORY:-}"
OUT_DIR="${ROOT_DIR}/target/build-runner-assets"
DOWNLOAD_LXC=true
DOWNLOAD_MACOS=true

usage() {
  cat <<'EOF'
usage: scripts/download-build-runner-release-assets.sh --run-id <github-run-id> [--out-dir <dir>] [--repo <owner/repo>] [--skip-lxc] [--skip-macos]

Download release artifacts from the manually triggered "release assets via
build-runner" GitHub Actions workflow and prepare merge-ready directories for
scripts/release-local.sh.

Prepared directories:
  <out-dir>/release-inputs/lxc
  <out-dir>/release-inputs/macos

Prepared env helper:
  <out-dir>/release-inputs/release-local.env.sh
  <out-dir>/release-inputs/release-local.env.ps1

Examples:
  scripts/download-build-runner-release-assets.sh --run-id 12345678901
  source target/build-runner-assets/release-inputs/release-local.env.sh
  scripts/release-local.sh v0.1.9

  scripts/download-build-runner-release-assets.sh --run-id 12345678901
  powershell -NoProfile -ExecutionPolicy Bypass -File target/build-runner-assets/release-inputs/release-local.env.ps1
  bash scripts/release-local.sh v0.1.9

  scripts/download-build-runner-release-assets.sh --run-id 12345678901 --skip-macos
  source target/build-runner-assets/release-inputs/release-local.env.sh
  scripts/release-local.sh v0.1.9
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --run-id)
      if [ "$#" -lt 2 ]; then
        echo "--run-id requires a GitHub Actions run ID" >&2
        exit 2
      fi
      RUN_ID="$2"
      shift 2
      ;;
    --out-dir)
      if [ "$#" -lt 2 ]; then
        echo "--out-dir requires a directory path" >&2
        exit 2
      fi
      OUT_DIR="$2"
      shift 2
      ;;
    --repo)
      if [ "$#" -lt 2 ]; then
        echo "--repo requires an OWNER/REPO value" >&2
        exit 2
      fi
      REPO="$2"
      shift 2
      ;;
    --skip-lxc)
      DOWNLOAD_LXC=false
      shift
      ;;
    --skip-macos)
      DOWNLOAD_MACOS=false
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [ -z "${RUN_ID}" ]; then
  echo "--run-id is required" >&2
  usage >&2
  exit 2
fi

if [ "${DOWNLOAD_LXC}" != true ] && [ "${DOWNLOAD_MACOS}" != true ]; then
  echo "nothing selected; remove --skip-lxc or --skip-macos" >&2
  exit 2
fi

GH_BIN="$(bash "${ROOT_DIR}/scripts/resolve-gh.sh")"
OUT_DIR_ABS="${OUT_DIR}"
case "${OUT_DIR_ABS}" in
  /*) ;;
  [A-Za-z]:/*) ;;
  *)
    OUT_DIR_ABS="$(cd "${ROOT_DIR}" && mkdir -p "${OUT_DIR}" && cd "${OUT_DIR}" && pwd)"
    ;;
esac

RAW_DIR="${OUT_DIR_ABS}/raw"
RELEASE_INPUTS_DIR="${OUT_DIR_ABS}/release-inputs"
LXC_DIR="${RELEASE_INPUTS_DIR}/lxc"
MACOS_DIR="${RELEASE_INPUTS_DIR}/macos"
ENV_FILE="${RELEASE_INPUTS_DIR}/release-local.env.sh"
ENV_FILE_PS1="${RELEASE_INPUTS_DIR}/release-local.env.ps1"

safe_reset_dir() {
  local dir="$1"
  if [ -z "${dir}" ] || [ "${dir}" = "/" ] || [ "${dir}" = "." ]; then
    echo "refusing to reset unsafe directory: ${dir}" >&2
    exit 1
  fi
  rm -rf "${dir}"
  mkdir -p "${dir}"
}

normalize_download_dir() {
  local dir="$1"
  local artifact="$2"
  local nested="${dir}/${artifact}"
  if [ -d "${nested}" ]; then
    shopt -s dotglob nullglob
    mv "${nested}"/* "${dir}/"
    shopt -u dotglob nullglob
    rmdir "${nested}"
  fi
}

download_artifact() {
  local artifact="$1"
  local dest="${RAW_DIR}/${artifact}"
  local cmd=("${GH_BIN}" run download "${RUN_ID}" -n "${artifact}" -D "${dest}")

  safe_reset_dir "${dest}"
  if [ -n "${REPO}" ]; then
    cmd=("${GH_BIN}" run download "${RUN_ID}" --repo "${REPO}" -n "${artifact}" -D "${dest}")
  fi
  "${cmd[@]}"
  normalize_download_dir "${dest}" "${artifact}"
}

copy_required_file() {
  local src="$1"
  local dest_dir="$2"
  if [ ! -f "${src}" ]; then
    echo "missing expected artifact file: ${src}" >&2
    exit 1
  fi
  cp "${src}" "${dest_dir}/"
}

safe_reset_dir "${RAW_DIR}"
safe_reset_dir "${RELEASE_INPUTS_DIR}"

if [ "${DOWNLOAD_LXC}" = true ]; then
  download_artifact "ccbg-lxc-package"
  mkdir -p "${LXC_DIR}"
  copy_required_file "${RAW_DIR}/ccbg-lxc-package/ccbg-lxc-package.tar.gz" "${LXC_DIR}"
  copy_required_file "${RAW_DIR}/ccbg-lxc-package/ccbg-lxc-package.tar.gz.sha256" "${LXC_DIR}"
fi

if [ "${DOWNLOAD_MACOS}" = true ]; then
  download_artifact "ccbg-macos-x86_64"
  download_artifact "ccbg-macos-arm64"
  mkdir -p "${MACOS_DIR}"
  copy_required_file "${RAW_DIR}/ccbg-macos-x86_64/ccbg-macos-x86_64.tar.gz" "${MACOS_DIR}"
  copy_required_file "${RAW_DIR}/ccbg-macos-x86_64/ccbg-macos-x86_64.tar.gz.sha256" "${MACOS_DIR}"
  copy_required_file "${RAW_DIR}/ccbg-macos-arm64/ccbg-macos-arm64.tar.gz" "${MACOS_DIR}"
  copy_required_file "${RAW_DIR}/ccbg-macos-arm64/ccbg-macos-arm64.tar.gz.sha256" "${MACOS_DIR}"
fi

{
  echo "# generated by scripts/download-build-runner-release-assets.sh"
  if [ "${DOWNLOAD_LXC}" = true ]; then
    printf "export CCBG_RELEASE_LXC_ASSET_DIR='%s'\n" "${LXC_DIR}"
  fi
  if [ "${DOWNLOAD_MACOS}" = true ]; then
    printf "export CCBG_RELEASE_MACOS_ASSET_DIR='%s'\n" "${MACOS_DIR}"
  fi
} > "${ENV_FILE}"

{
  echo "# generated by scripts/download-build-runner-release-assets.sh"
  if [ "${DOWNLOAD_LXC}" = true ]; then
    printf "\$env:CCBG_RELEASE_LXC_ASSET_DIR = '%s'\n" "${LXC_DIR}"
  fi
  if [ "${DOWNLOAD_MACOS}" = true ]; then
    printf "\$env:CCBG_RELEASE_MACOS_ASSET_DIR = '%s'\n" "${MACOS_DIR}"
  fi
} > "${ENV_FILE_PS1}"

printf 'prepared build-runner release inputs under %s\n' "${RELEASE_INPUTS_DIR}"
if [ "${DOWNLOAD_LXC}" = true ]; then
  printf '  lxc: %s\n' "${LXC_DIR}"
fi
if [ "${DOWNLOAD_MACOS}" = true ]; then
  printf '  macos: %s\n' "${MACOS_DIR}"
fi
printf '  env: %s\n' "${ENV_FILE}"
printf '  env(ps1): %s\n' "${ENV_FILE_PS1}"
printf '\nnext step:\n'
printf '  source %q\n' "${ENV_FILE}"
printf '  scripts/release-local.sh <tag>\n'
printf '\npowershell next step:\n'
printf '  . .\\target\\build-runner-assets\\release-inputs\\release-local.env.ps1\n'
printf '  bash scripts/release-local.sh <tag>\n'
